# Generated by Django 5.2.3 on 2025-07-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remaining',
            field=models.IntegerField(default=2, verbose_name='Остаток'),
            preserve_default=False,
        ),
    ]
